site_name: Blood Magic
site_favicon: docs/favicon.ico
repo_url: https://github.com/ModDocs/bloodmagic
strict: true

markdown_extensions:
  - smarty
  - urlize
  - tables
  - fenced_code

pages:
  - Home: 'index.md'
  - Rituals:
    - Ritual of the Full Spring: 'rituals/ritualOfTheFullspring.md'
    - Serenade of the Nether: 'rituals/serenadeOfTheNether.md'
    - Ritual of the Green Grove: 'rituals/ritualOfTheGreenGrove.md'
    - Ritual of High Jump: 'rituals/ritualOfHighJump.md'
